{% set name = "alchemiscale" %}
{% set version = "0.5.2" %}

package:
  name: alchemiscale
  version: {{ version }}

source:
  url: https://github.com/openforcefield/alchemiscale/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d27e2aeec3c3efa0858ca58b1a0bb73e241f55dfec010040c8e1485a1647c49a

build:
  number: 0

outputs:
  - name: alchemiscale-server
    script: build_package.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.10
        - pip
        - setuptools
        - versioningit
      run:
        - python >=3.10
        - gufe>=1.0.0
        - requests
        - click
        - httpx
        - pydantic<2.0a0
        - async-lru

        ## state store
        - neo4j-python-driver
        - py2neo
        - monotonic

        ## object store
        - boto3        # aws s3

        ## api(s)
        - fastapi
        - uvicorn
        - gunicorn
        - python-jose
        - passlib
        - bcrypt
        - python-multipart
        - starlette
        - cryptography

    test:
      imports:
        - alchemiscale
      files:
        - test_stack_imports.py
      commands:
        - python test_stack_imports.py

  - name: alchemiscale-compute
    script: build_package.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.10
        - pip
        - setuptools
        - versioningit
      run:
        - python >=3.10
        - gufe>=1.0.0
        - requests
        - click
        - httpx
        - pydantic<2.0a0
        - async-lru

    test:
      imports:
        - alchemiscale
      files:
        - test_stack_imports.py
      commands:
        - python test_stack_imports.py

  - name: alchemiscale-client
    script: build_package.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.10
        - pip
        - setuptools
        - versioningit
      run:
        - python >=3.10
        - gufe>=1.0.0
        - requests
        - click
        - httpx
        - pydantic<2.0a0
        - rich
        - async-lru
        - nest-asyncio

    test:
      imports:
        - alchemiscale
      files:
        - test_stack_imports.py
      commands:
        - python test_stack_imports.py

about:
  home: https://github.com/openforcefield/alchemiscale
  summary: 'high-throughput alchemical free energy execution system'
  description: |
    a high-throughput alchemical free energy execution system 
    for use with HPC, cloud, bare metal, and Folding@Home 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.alchemiscale.org/
  dev_url: https://github.com/openforcefield/alchemiscale

extra:
  recipe-maintainers:
    - dotsdl
    - hmacdope
    - mikemhenry
