{% set python_min = "3.11" %}
{% set name = "alchemiscale" %}
{% set version = "0.6.1" %}

package:
  name: alchemiscale
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/alchemiscale/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4804dc95f53226553ca25716e51a99ce46e0ba74033f15316f8a00549f9782c1

build:
  number: 0

outputs:
  - name: alchemiscale-server
    script: build_package.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - versioningit
      run:
        - python >={{ python_min }}
        - gufe >=1.2.0
        - requests
        - click
        - httpx
        - pydantic >2
        - async-lru

        ## state store
        - neo4j-python-driver
        - py2neo
        - monotonic

        ## object store
        - boto3        # aws s3

        ## api(s)
        - fastapi
        - uvicorn
        - gunicorn
        - python-jose
        - passlib
        - bcrypt
        - python-multipart
        - starlette
        - cryptography

        ## temporary pins
        - openff-units <=0.2.2
        - openff-interchange <=0.4.1    # https://github.com/openmm/openmmforcefields/issues/365

    test:
      requires:
        - python {{ python_min }}
      imports:
        - alchemiscale
      files:
        - test_stack_imports.py
      commands:
        - python test_stack_imports.py

  - name: alchemiscale-compute
    script: build_package.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - versioningit
      run:
        - python >={{ python_min }}
        - gufe >=1.2.0
        - requests
        - click
        - httpx
        - pydantic >2
        - async-lru

        ## temporary pins
        - openff-units <=0.2.2
        - openff-interchange <=0.4.1    # https://github.com/openmm/openmmforcefields/issues/365

    test:
      requires:
        - python {{ python_min }}
      imports:
        - alchemiscale
      files:
        - test_stack_imports.py
      commands:
        - python test_stack_imports.py

  - name: alchemiscale-client
    script: build_package.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - versioningit
      run:
        - python >={{ python_min }}
        - gufe >=1.2.0
        - requests
        - click
        - httpx
        - pydantic >2
        - rich
        - async-lru
        - nest-asyncio

        ## temporary pins
        - openff-units <=0.2.2
        - openff-interchange <=0.4.1    # https://github.com/openmm/openmmforcefields/issues/365

    test:
      requires:
        - python {{ python_min }}
      imports:
        - alchemiscale
      files:
        - test_stack_imports.py
      commands:
        - python test_stack_imports.py

about:
  home: https://github.com/OpenFreeEnergy/alchemiscale
  summary: 'high-throughput alchemical free energy execution system'
  description: |
    a high-throughput alchemical free energy execution system 
    for use with HPC, cloud, bare metal, and Folding@Home 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.alchemiscale.org/
  dev_url: https://github.com/OpenFreeEnergy/alchemiscale

extra:
  recipe-maintainers:
    - dotsdl
    - hmacdope
    - mikemhenry
