{% set name = "alchemiscale" %}
{% set version = "0.5.0" %}

package:
  name: alchemiscale
  version: {{ version }}

source:
  url: https://github.com/openforcefield/alchemiscale/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1730dfdcda8d51c5f3b44338279741eae6667773a84e36a0869167d2c45757ed

build:
  number: 0

outputs:
  - name: alchemiscale-compute
    script: build_package.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.9
        - pip
        - versioningit
      run:
        - python >=3.9
        - gufe=0.9.5
        - openfe=0.14.0
        - requests
        - click
        - httpx
        - pydantic<2.0a0
        - openmoltools
        - cloudpathlib
        - dask
        - distributed
        - numba
        - pymbar >=3.0.6,<4.0a0
        - async-lru

    test:
      imports:
        - alchemiscale
      requires:
        - pip
      commands:
        - pip check

  - name: alchemiscale-client
    script: build_package.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.9
        - pip
        - versioningit
      run:
        - python >=3.9
        - gufe=0.9.5
        - openfe=0.14.0
        - requests
        - click
        - httpx
        - pydantic<2.0a0
        - rich
        - openmoltools
        - cloudpathlib
        - dask
        - distributed
        - numba
        - pymbar >=3.0.6,<4.0a0
        - async-lru
        - nest-asyncio


    test:
      imports:
        - alchemiscale
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/openforcefield/alchemiscale
  summary: 'high-throughput alchemical free energy execution system'
  description: |
    a high-throughput alchemical free energy execution system 
    for use with HPC, cloud, bare metal, and Folding@Home 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.alchemiscale.org/
  dev_url: https://github.com/openforcefield/alchemiscale

extra:
  recipe-maintainers:
    - dotsdl
    - hmacdope
    - mikemhenry
